sudo: false
language: python
python:
  - "2.7"
env:
  global:
    - NIFTY_TRAVIS_CACHE_REPO=https://github.com/nimbis/travis-cache-public.git
install:
  - pip install -r requirements.txt
before_script:
  - git clone https://github.com/nimbis/nifty.git ./.nifty
script:
  - source .nifty/nifty-script
  - verify_coverage_improvement
  - make pep8
  - make test
  - make coverage
  - make doc
